// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTaskMoloko.Contexts;

namespace TestTaskMoloko.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190204143615_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestTaskMoloko.Models.CriticalError", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Error")
                        .HasColumnName("error");

                    b.HasKey("Id");

                    b.ToTable("CriticalErrors");
                });

            modelBuilder.Entity("TestTaskMoloko.Models.Message", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsReceived")
                        .HasColumnName("is_received");

                    b.Property<string>("Receiver")
                        .HasColumnName("receiver")
                        .HasMaxLength(30);

                    b.Property<string>("Sender")
                        .HasColumnName("sender")
                        .HasMaxLength(30);

                    b.Property<string>("SmsText");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TestTaskMoloko.Models.MessageResponse", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MsgErrCode");

                    b.Property<long>("ServerId");

                    b.Property<string>("SmsText")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.ToTable("MessageSendHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
